[build]
  publish = "dist"
  command = "pnpm run build"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[dev]
  command = "pnpm run dev"

[[headers]]
  for = "/admin/*"
    [headers.values]
    Cache-Control = "no-cache" 